# Generated by CoffeeScript 1.7.1
DropDown = undefined
$(window).scroll ->
  if $(".navbar").offset().top > 550
    $(".navbar-fixed-top").addClass "top-nav-collapse"
  else
    $(".navbar-fixed-top").removeClass "top-nav-collapse"
  return

$ ->
  $("#view-more-link,.page-scroll a,.cta-scroll").bind "click", (e) ->
    t = undefined
    t = undefined
    t = $(this)
    $("html, body").stop().animate
      scrollTop: $(t.attr("href")).offset().top + ((if $(window).width() < 480 then -50 else 0))
    , 1500, "easeInOutExpo"
    e.preventDefault()
    return

  return

DropDown = (el) ->
  @dd = el
  @placeholder = @dd.children("h4")
  @opts = @dd.find("ul.dropdown > li")
  @val = ""
  @index = -1
  @initEvents()
  return

DropDown:: =
  initEvents: ->
    obj = undefined
    obj = this
    obj.dd.on "click", (event) ->
      $(this).toggleClass "active"
      false

    obj.opts.on "click", ->
      console.log "lawl"
      opt = undefined
      opt = $(this)
      obj.val = opt.text()
      obj.index = opt.index()
      navigate_link = $('.dropdown').find('li').find('a').eq(obj.index).attr('href')
      $('#section-navigator').attr('href',navigate_link)
      obj.placeholder.text obj.val
      return

    return

  getValue: ->
    @val

  getIndex: ->
    @index

$ ->
  dd = undefined
  dd = new DropDown($("#dd"))
  $(document).click ->
    $(".selectfield-dropdown").removeClass "active"
    return

  return

$('#subscribe-form').submit ->
  $('form').fadeOut(500).delay(100)
  $('.subscribe-thanks').fadeIn(1500)
  form = $(this)
  url = $(this).attr('action')
  data = $(this).serialize()
  $.ajax
    type: "GET"
    url: url
    dataType: 'json'
    contentType: "application/json; charset=utf-8"
    data: data
  false

$ ->
  email_field = $('#MERGE0')
  valid_email = (email) ->
    email_regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/
    String(email).match email_regex

  email_field.on "input", ->
    if valid_email(email_field.val())
      email_field.removeClass("error-field")
      $('#subscribe-form-btn').removeAttr('disabled')
      $('#subscribe-form-btn').removeClass('disabled-btn')
    else
      email_field.addClass("error-field")
      $('#subscribe-form-btn').attr('disabled','disabled')
      $('#subscribe-form-btn').addClass('disabled-btn')

# Carousel pause autoplay
$(".carousel").carousel
  pause: true
  interval: false

# Navbar autoclose on mobile
$(window).resize ->
  if $(window).width() < 480
    $(".navbar-nav").on "click", "li a", ->
      $(".navbar-collapse").collapse "hide"
      return

$ ->
  if $(window).width() < 480
    $(".navbar-nav").on "click", "li a", ->
      $(".navbar-collapse").collapse "hide"
      return

# Fix for scroll on dropdown
$(".dropdown").bind "mousewheel DOMMouseScroll", (e) ->
  e0 = e.originalEvent
  delta = e0.wheelDelta or -e0.detail
  @scrollTop += ((if delta < 0 then 1 else -1)) * 30
  e.preventDefault()
  return
